app1/urls.py
from django.urls import path
from app1.views import *

app_name='something'
urlpatterns=[
    path('ganapathi/',ganapathi,name='ganapathi'),
    
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='somethinggg'
urlpatterns=[
    path('job/',job,name='job'),
]

project16/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def ganapathi(request):
    return render(request,'ganapathi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def job(request):
    return render(request,'job.html')

templates/ganapathi.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ganapathi</title>
    
        <link rel='stylesheet' href='{% static 'css/c1.css' %}'/>
    
</head>
<body>
    <center>
        <h1> ganapathibappa moriyaa........</h1>
        <img src="{% static 'images/ganapayya.jpeg' %}" width="400" hight="500"/>
       <h1> <a href="{% url 'somethinggg:job' %}">go to job</a></h1>
    </center>
</body>
</html>`

templates/job.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>job</title>
    
        <link rel='stylesheet' href='{% static 'css/c2.css' %}'/>
    
</head>
<body>
    <center>
        <h1>
             really need a job
        </h1>
        <img src="{% static 'images/image1.jpeg '%}" width="400" hight="500"/>
        <h1><a href="{% url 'something:ganapathi' %}">go to god</a></h1>
    </center>
</body>
</html>